// <auto-generated />
using System;
using BezorgDirect.BezorgersApplicatie.BusinessLogic.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BezorgDirect.BezorgersApplicatie.BusinessLogic.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20191104155102_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Availability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<Guid>("DelivererId");

                    b.Property<TimeSpan>("EndTime");

                    b.Property<TimeSpan>("StartTime");

                    b.HasKey("Id");

                    b.HasIndex("DelivererId");

                    b.ToTable("Availabilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e210c6e9-a284-4733-89ec-47bd8da81f57"),
                            Date = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            DelivererId = new Guid("1c8d26ac-0879-4bd4-aa45-ede7206c315d"),
                            EndTime = new TimeSpan(699621446676),
                            StartTime = new TimeSpan(606621446670)
                        },
                        new
                        {
                            Id = new Guid("6e1acab9-a426-43f1-81e9-e9a98b88398a"),
                            Date = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            DelivererId = new Guid("a6578db0-5e35-4a6b-967b-2d546e16b6f7"),
                            EndTime = new TimeSpan(699621456335),
                            StartTime = new TimeSpan(606621456329)
                        },
                        new
                        {
                            Id = new Guid("8216c5a9-bda8-4294-82ec-2af25bd0b19e"),
                            Date = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            DelivererId = new Guid("4a18c314-3c45-4eea-b893-680eb09c1abe"),
                            EndTime = new TimeSpan(699621456692),
                            StartTime = new TimeSpan(606621456686)
                        },
                        new
                        {
                            Id = new Guid("f56dd88e-f985-4daa-afee-ff377f6008a7"),
                            Date = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            DelivererId = new Guid("b97b134c-9f3d-4bef-9085-85b16b2f0cff"),
                            EndTime = new TimeSpan(699621456726),
                            StartTime = new TimeSpan(606621456721)
                        },
                        new
                        {
                            Id = new Guid("4bdead21-875e-46b3-9dcf-4a02ae8cede4"),
                            Date = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            DelivererId = new Guid("1566979b-9fa6-4a51-8e67-08509ce79106"),
                            EndTime = new TimeSpan(699621456742),
                            StartTime = new TimeSpan(606621456737)
                        },
                        new
                        {
                            Id = new Guid("3f414f30-48c3-4108-bf1e-88ec9007f45e"),
                            Date = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            DelivererId = new Guid("77f3c372-e321-4263-ba7a-0f86ce51de56"),
                            EndTime = new TimeSpan(699621456760),
                            StartTime = new TimeSpan(606621456754)
                        },
                        new
                        {
                            Id = new Guid("64a84684-529d-4bf4-9213-39c0c64226e8"),
                            Date = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            DelivererId = new Guid("fa8ec550-2863-4f01-82df-488d66004a60"),
                            EndTime = new TimeSpan(699621456777),
                            StartTime = new TimeSpan(606621456774)
                        },
                        new
                        {
                            Id = new Guid("41d5e2c0-ed75-44a7-987a-b6773a18eaef"),
                            Date = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            DelivererId = new Guid("c26682bd-d8bf-4698-a00e-02d059a2498d"),
                            EndTime = new TimeSpan(699621456797),
                            StartTime = new TimeSpan(606621456791)
                        },
                        new
                        {
                            Id = new Guid("bbb93360-88f1-4e87-8406-7fc5bc587652"),
                            Date = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            DelivererId = new Guid("546210b1-6ec8-4d64-b058-b3fa7e0740aa"),
                            EndTime = new TimeSpan(699621456823),
                            StartTime = new TimeSpan(606621456818)
                        },
                        new
                        {
                            Id = new Guid("e13a9f39-0d81-4bbf-af63-29615e981171"),
                            Date = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            DelivererId = new Guid("5fc08418-6e23-4de8-88b0-1c513ddaf40d"),
                            EndTime = new TimeSpan(699621456842),
                            StartTime = new TimeSpan(606621456836)
                        },
                        new
                        {
                            Id = new Guid("32325d52-a8c8-47b1-9b81-8d60b86e4120"),
                            Date = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            DelivererId = new Guid("f2f458f3-819e-46b3-be44-554f6a2fad93"),
                            EndTime = new TimeSpan(699621456859),
                            StartTime = new TimeSpan(606621456855)
                        });
                });

            modelBuilder.Entity("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CurrentId");

                    b.Property<double?>("CustomerDistanceInKilometers");

                    b.Property<DateTime?>("CustomerETA");

                    b.Property<Guid>("CustomerId");

                    b.Property<string>("CustomerPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<DateTime?>("DeliveredAt");

                    b.Property<Guid?>("DelivererId");

                    b.Property<DateTime>("DueDate");

                    b.Property<int>("PaymentMethod");

                    b.Property<double>("Price");

                    b.Property<Guid?>("StartedAtId");

                    b.Property<int>("Status");

                    b.Property<double?>("Tip");

                    b.Property<int>("Vehicle");

                    b.Property<double?>("WarehouseDistanceInKilometers");

                    b.Property<DateTime?>("WarehouseETA");

                    b.Property<Guid>("WarehouseId");

                    b.Property<DateTime?>("WarehousePickUpAt");

                    b.HasKey("Id");

                    b.HasIndex("CurrentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DelivererId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Deliveries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d5dd904-43ab-4ee4-9b72-78ec0caf629b"),
                            CurrentId = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3"),
                            CustomerDistanceInKilometers = 5.7000000000000002,
                            CustomerETA = new DateTime(2019, 11, 4, 17, 0, 2, 145, DateTimeKind.Local).AddTicks(8072),
                            CustomerId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerPhoneNumber = "0612345678",
                            DelivererId = new Guid("a6578db0-5e35-4a6b-967b-2d546e16b6f7"),
                            DueDate = new DateTime(2019, 11, 4, 18, 51, 2, 145, DateTimeKind.Local).AddTicks(7988),
                            PaymentMethod = 0,
                            Price = 14.26,
                            StartedAtId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            Status = 3,
                            Vehicle = 4,
                            WarehouseDistanceInKilometers = 13.6,
                            WarehouseETA = new DateTime(2019, 11, 4, 16, 30, 2, 145, DateTimeKind.Local).AddTicks(8032),
                            WarehouseId = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3"),
                            WarehousePickUpAt = new DateTime(2019, 11, 4, 16, 51, 2, 145, DateTimeKind.Local).AddTicks(8066)
                        },
                        new
                        {
                            Id = new Guid("082f1eda-2985-4d2b-8add-80487f8edf66"),
                            CustomerDistanceInKilometers = 5.7000000000000002,
                            CustomerETA = new DateTime(2019, 11, 4, 17, 0, 2, 148, DateTimeKind.Local).AddTicks(8469),
                            CustomerId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerPhoneNumber = "0612345678",
                            DueDate = new DateTime(2019, 11, 4, 18, 51, 2, 148, DateTimeKind.Local).AddTicks(8447),
                            PaymentMethod = 0,
                            Price = 53.68,
                            Status = 1,
                            Vehicle = 4,
                            WarehouseId = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3")
                        },
                        new
                        {
                            Id = new Guid("3efb4583-bde7-4038-93ef-c7d30b845dd0"),
                            CurrentId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerDistanceInKilometers = 5.7000000000000002,
                            CustomerETA = new DateTime(2019, 11, 4, 16, 51, 2, 148, DateTimeKind.Local).AddTicks(9235),
                            CustomerId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerPhoneNumber = "0612345678",
                            DeliveredAt = new DateTime(2019, 11, 4, 16, 50, 2, 148, DateTimeKind.Local).AddTicks(9241),
                            DelivererId = new Guid("77f3c372-e321-4263-ba7a-0f86ce51de56"),
                            DueDate = new DateTime(2019, 11, 4, 18, 51, 2, 148, DateTimeKind.Local).AddTicks(9208),
                            PaymentMethod = 1,
                            Price = 14.26,
                            StartedAtId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            Status = 4,
                            Vehicle = 4,
                            WarehouseDistanceInKilometers = 13.6,
                            WarehouseETA = new DateTime(2019, 11, 4, 16, 21, 2, 148, DateTimeKind.Local).AddTicks(9224),
                            WarehouseId = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3"),
                            WarehousePickUpAt = new DateTime(2019, 11, 4, 16, 42, 2, 148, DateTimeKind.Local).AddTicks(9229)
                        },
                        new
                        {
                            Id = new Guid("1e1909e9-de01-4221-bea1-80198de9254d"),
                            CurrentId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerDistanceInKilometers = 5.7000000000000002,
                            CustomerETA = new DateTime(2019, 11, 4, 16, 51, 2, 148, DateTimeKind.Local).AddTicks(9862),
                            CustomerId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerPhoneNumber = "0612345678",
                            DeliveredAt = new DateTime(2019, 11, 4, 16, 51, 2, 148, DateTimeKind.Local).AddTicks(9866),
                            DelivererId = new Guid("77f3c372-e321-4263-ba7a-0f86ce51de56"),
                            DueDate = new DateTime(2019, 11, 4, 18, 51, 2, 148, DateTimeKind.Local).AddTicks(9845),
                            PaymentMethod = 1,
                            Price = 14.26,
                            StartedAtId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            Status = 4,
                            Tip = 2.5,
                            Vehicle = 4,
                            WarehouseDistanceInKilometers = 13.6,
                            WarehouseETA = new DateTime(2019, 11, 4, 16, 21, 2, 148, DateTimeKind.Local).AddTicks(9852),
                            WarehouseId = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3"),
                            WarehousePickUpAt = new DateTime(2019, 11, 4, 16, 42, 2, 148, DateTimeKind.Local).AddTicks(9859)
                        },
                        new
                        {
                            Id = new Guid("7cb4d484-5fbc-4098-a4f5-bccfa1dd4a4a"),
                            CurrentId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerDistanceInKilometers = 5.7000000000000002,
                            CustomerETA = new DateTime(2019, 11, 4, 16, 51, 2, 149, DateTimeKind.Local).AddTicks(190),
                            CustomerId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerPhoneNumber = "0612345678",
                            DeliveredAt = new DateTime(2019, 11, 4, 16, 52, 2, 149, DateTimeKind.Local).AddTicks(194),
                            DelivererId = new Guid("fa8ec550-2863-4f01-82df-488d66004a60"),
                            DueDate = new DateTime(2019, 11, 4, 18, 51, 2, 149, DateTimeKind.Local).AddTicks(176),
                            PaymentMethod = 1,
                            Price = 14.26,
                            StartedAtId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            Status = 4,
                            Vehicle = 4,
                            WarehouseDistanceInKilometers = 13.6,
                            WarehouseETA = new DateTime(2019, 11, 4, 16, 21, 2, 149, DateTimeKind.Local).AddTicks(184),
                            WarehouseId = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3"),
                            WarehousePickUpAt = new DateTime(2019, 11, 4, 16, 42, 2, 149, DateTimeKind.Local).AddTicks(187)
                        },
                        new
                        {
                            Id = new Guid("061d5bc1-62f3-4372-b354-77a4b8be26c0"),
                            CurrentId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerDistanceInKilometers = 5.7000000000000002,
                            CustomerETA = new DateTime(2019, 11, 4, 16, 51, 2, 149, DateTimeKind.Local).AddTicks(448),
                            CustomerId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerPhoneNumber = "0612345678",
                            DeliveredAt = new DateTime(2019, 11, 4, 16, 52, 2, 149, DateTimeKind.Local).AddTicks(452),
                            DelivererId = new Guid("fa8ec550-2863-4f01-82df-488d66004a60"),
                            DueDate = new DateTime(2019, 11, 4, 18, 51, 2, 149, DateTimeKind.Local).AddTicks(429),
                            PaymentMethod = 1,
                            Price = 14.26,
                            StartedAtId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            Status = 4,
                            Tip = 1.0,
                            Vehicle = 4,
                            WarehouseDistanceInKilometers = 13.6,
                            WarehouseETA = new DateTime(2019, 11, 4, 16, 21, 2, 149, DateTimeKind.Local).AddTicks(436),
                            WarehouseId = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3"),
                            WarehousePickUpAt = new DateTime(2019, 11, 4, 16, 42, 2, 149, DateTimeKind.Local).AddTicks(443)
                        },
                        new
                        {
                            Id = new Guid("819363c4-434f-4934-bc2b-1d7de4ddef7a"),
                            CurrentId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerDistanceInKilometers = 5.7000000000000002,
                            CustomerETA = new DateTime(2019, 11, 4, 16, 51, 2, 149, DateTimeKind.Local).AddTicks(693),
                            CustomerId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerPhoneNumber = "0612345678",
                            DeliveredAt = new DateTime(2019, 11, 4, 17, 49, 2, 149, DateTimeKind.Local).AddTicks(697),
                            DelivererId = new Guid("c26682bd-d8bf-4698-a00e-02d059a2498d"),
                            DueDate = new DateTime(2019, 11, 4, 18, 51, 2, 149, DateTimeKind.Local).AddTicks(672),
                            PaymentMethod = 1,
                            Price = 14.26,
                            StartedAtId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            Status = 4,
                            Vehicle = 4,
                            WarehouseDistanceInKilometers = 13.6,
                            WarehouseETA = new DateTime(2019, 11, 4, 16, 21, 2, 149, DateTimeKind.Local).AddTicks(680),
                            WarehouseId = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3"),
                            WarehousePickUpAt = new DateTime(2019, 11, 4, 16, 42, 2, 149, DateTimeKind.Local).AddTicks(687)
                        },
                        new
                        {
                            Id = new Guid("0415d421-3359-4117-a697-092186ae2569"),
                            CurrentId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerDistanceInKilometers = 5.7000000000000002,
                            CustomerETA = new DateTime(2019, 11, 4, 16, 51, 2, 149, DateTimeKind.Local).AddTicks(1008),
                            CustomerId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerPhoneNumber = "0612345678",
                            DeliveredAt = new DateTime(2019, 11, 4, 17, 37, 2, 149, DateTimeKind.Local).AddTicks(1014),
                            DelivererId = new Guid("c26682bd-d8bf-4698-a00e-02d059a2498d"),
                            DueDate = new DateTime(2019, 11, 4, 18, 51, 2, 149, DateTimeKind.Local).AddTicks(989),
                            PaymentMethod = 1,
                            Price = 14.26,
                            StartedAtId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            Status = 4,
                            Vehicle = 4,
                            WarehouseDistanceInKilometers = 13.6,
                            WarehouseETA = new DateTime(2019, 11, 4, 16, 21, 2, 149, DateTimeKind.Local).AddTicks(997),
                            WarehouseId = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3"),
                            WarehousePickUpAt = new DateTime(2019, 11, 4, 16, 42, 2, 149, DateTimeKind.Local).AddTicks(1003)
                        },
                        new
                        {
                            Id = new Guid("8cd77e0d-784b-4440-80e9-cd889395a420"),
                            CurrentId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerDistanceInKilometers = 5.7000000000000002,
                            CustomerETA = new DateTime(2019, 11, 4, 16, 51, 2, 149, DateTimeKind.Local).AddTicks(1272),
                            CustomerId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerPhoneNumber = "0612345678",
                            DeliveredAt = new DateTime(2019, 11, 4, 17, 7, 2, 149, DateTimeKind.Local).AddTicks(1277),
                            DelivererId = new Guid("546210b1-6ec8-4d64-b058-b3fa7e0740aa"),
                            DueDate = new DateTime(2019, 11, 4, 18, 51, 2, 149, DateTimeKind.Local).AddTicks(1253),
                            PaymentMethod = 1,
                            Price = 14.26,
                            StartedAtId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            Status = 4,
                            Vehicle = 4,
                            WarehouseDistanceInKilometers = 13.6,
                            WarehouseETA = new DateTime(2019, 11, 4, 16, 21, 2, 149, DateTimeKind.Local).AddTicks(1262),
                            WarehouseId = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3"),
                            WarehousePickUpAt = new DateTime(2019, 11, 4, 16, 42, 2, 149, DateTimeKind.Local).AddTicks(1267)
                        },
                        new
                        {
                            Id = new Guid("8800377f-f8c9-4db8-8fed-60b4fa2b4bb6"),
                            CurrentId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerDistanceInKilometers = 5.7000000000000002,
                            CustomerETA = new DateTime(2019, 11, 4, 16, 51, 2, 149, DateTimeKind.Local).AddTicks(1513),
                            CustomerId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerPhoneNumber = "0612345678",
                            DeliveredAt = new DateTime(2019, 11, 4, 17, 19, 2, 149, DateTimeKind.Local).AddTicks(1516),
                            DelivererId = new Guid("546210b1-6ec8-4d64-b058-b3fa7e0740aa"),
                            DueDate = new DateTime(2019, 11, 4, 18, 51, 2, 149, DateTimeKind.Local).AddTicks(1497),
                            PaymentMethod = 1,
                            Price = 14.26,
                            StartedAtId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            Status = 4,
                            Vehicle = 4,
                            WarehouseDistanceInKilometers = 13.6,
                            WarehouseETA = new DateTime(2019, 11, 4, 16, 21, 2, 149, DateTimeKind.Local).AddTicks(1504),
                            WarehouseId = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3"),
                            WarehousePickUpAt = new DateTime(2019, 11, 4, 16, 42, 2, 149, DateTimeKind.Local).AddTicks(1510)
                        },
                        new
                        {
                            Id = new Guid("c4f626f8-e626-45b9-8548-b1d922a49e0d"),
                            CurrentId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerDistanceInKilometers = 5.7000000000000002,
                            CustomerETA = new DateTime(2019, 11, 4, 16, 51, 2, 149, DateTimeKind.Local).AddTicks(1848),
                            CustomerId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerPhoneNumber = "0612345678",
                            DeliveredAt = new DateTime(2019, 11, 4, 17, 33, 2, 149, DateTimeKind.Local).AddTicks(1854),
                            DelivererId = new Guid("5fc08418-6e23-4de8-88b0-1c513ddaf40d"),
                            DueDate = new DateTime(2019, 11, 4, 18, 51, 2, 149, DateTimeKind.Local).AddTicks(1830),
                            PaymentMethod = 1,
                            Price = 14.26,
                            StartedAtId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            Status = 4,
                            Vehicle = 4,
                            WarehouseDistanceInKilometers = 13.6,
                            WarehouseETA = new DateTime(2019, 11, 4, 16, 21, 2, 149, DateTimeKind.Local).AddTicks(1838),
                            WarehouseId = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3"),
                            WarehousePickUpAt = new DateTime(2019, 11, 4, 16, 42, 2, 149, DateTimeKind.Local).AddTicks(1843)
                        },
                        new
                        {
                            Id = new Guid("4aea94b7-a21f-472f-be50-154fead4ac8c"),
                            CurrentId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerDistanceInKilometers = 5.7000000000000002,
                            CustomerETA = new DateTime(2019, 11, 4, 16, 51, 2, 149, DateTimeKind.Local).AddTicks(2106),
                            CustomerId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerPhoneNumber = "0612345678",
                            DeliveredAt = new DateTime(2019, 11, 4, 17, 24, 2, 149, DateTimeKind.Local).AddTicks(2109),
                            DelivererId = new Guid("5fc08418-6e23-4de8-88b0-1c513ddaf40d"),
                            DueDate = new DateTime(2019, 11, 4, 18, 51, 2, 149, DateTimeKind.Local).AddTicks(2089),
                            PaymentMethod = 1,
                            Price = 14.26,
                            StartedAtId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            Status = 4,
                            Vehicle = 4,
                            WarehouseDistanceInKilometers = 13.6,
                            WarehouseETA = new DateTime(2019, 11, 4, 16, 21, 2, 149, DateTimeKind.Local).AddTicks(2096),
                            WarehouseId = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3"),
                            WarehousePickUpAt = new DateTime(2019, 11, 4, 16, 42, 2, 149, DateTimeKind.Local).AddTicks(2102)
                        },
                        new
                        {
                            Id = new Guid("3558b0eb-af94-4e37-b94a-8d82500cca37"),
                            CurrentId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerDistanceInKilometers = 5.7000000000000002,
                            CustomerETA = new DateTime(2019, 11, 4, 16, 51, 2, 149, DateTimeKind.Local).AddTicks(2361),
                            CustomerId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerPhoneNumber = "0612345678",
                            DeliveredAt = new DateTime(2019, 11, 4, 16, 55, 2, 149, DateTimeKind.Local).AddTicks(2367),
                            DelivererId = new Guid("f2f458f3-819e-46b3-be44-554f6a2fad93"),
                            DueDate = new DateTime(2019, 11, 4, 18, 51, 2, 149, DateTimeKind.Local).AddTicks(2343),
                            PaymentMethod = 1,
                            Price = 14.26,
                            StartedAtId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            Status = 4,
                            Vehicle = 4,
                            WarehouseDistanceInKilometers = 13.6,
                            WarehouseETA = new DateTime(2019, 11, 4, 16, 21, 2, 149, DateTimeKind.Local).AddTicks(2351),
                            WarehouseId = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3"),
                            WarehousePickUpAt = new DateTime(2019, 11, 4, 16, 42, 2, 149, DateTimeKind.Local).AddTicks(2356)
                        },
                        new
                        {
                            Id = new Guid("54b90b3c-f3e9-47cc-a507-7e0a8fea7fb0"),
                            CurrentId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerDistanceInKilometers = 5.7000000000000002,
                            CustomerETA = new DateTime(2019, 11, 4, 16, 51, 2, 149, DateTimeKind.Local).AddTicks(2670),
                            CustomerId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerPhoneNumber = "0612345678",
                            DeliveredAt = new DateTime(2019, 11, 4, 16, 59, 2, 149, DateTimeKind.Local).AddTicks(2676),
                            DelivererId = new Guid("f2f458f3-819e-46b3-be44-554f6a2fad93"),
                            DueDate = new DateTime(2019, 11, 4, 18, 51, 2, 149, DateTimeKind.Local).AddTicks(2649),
                            PaymentMethod = 1,
                            Price = 14.26,
                            StartedAtId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            Status = 4,
                            Vehicle = 4,
                            WarehouseDistanceInKilometers = 13.6,
                            WarehouseETA = new DateTime(2019, 11, 4, 16, 21, 2, 149, DateTimeKind.Local).AddTicks(2658),
                            WarehouseId = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3"),
                            WarehousePickUpAt = new DateTime(2019, 11, 4, 16, 42, 2, 149, DateTimeKind.Local).AddTicks(2664)
                        },
                        new
                        {
                            Id = new Guid("9c90af37-6ead-4b3c-ba11-d1c2e8634bba"),
                            CurrentId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerDistanceInKilometers = 5.7000000000000002,
                            CustomerETA = new DateTime(2019, 11, 4, 16, 51, 2, 149, DateTimeKind.Local).AddTicks(2926),
                            CustomerId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerPhoneNumber = "0612345678",
                            DeliveredAt = new DateTime(2019, 11, 4, 16, 59, 2, 149, DateTimeKind.Local).AddTicks(2930),
                            DelivererId = new Guid("1566979b-9fa6-4a51-8e67-08509ce79106"),
                            DueDate = new DateTime(2019, 11, 4, 18, 51, 2, 149, DateTimeKind.Local).AddTicks(2909),
                            PaymentMethod = 1,
                            Price = 14.26,
                            StartedAtId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            Status = 4,
                            Vehicle = 4,
                            WarehouseDistanceInKilometers = 13.6,
                            WarehouseETA = new DateTime(2019, 11, 4, 16, 21, 2, 149, DateTimeKind.Local).AddTicks(2918),
                            WarehouseId = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3"),
                            WarehousePickUpAt = new DateTime(2019, 11, 4, 16, 42, 2, 149, DateTimeKind.Local).AddTicks(2922)
                        },
                        new
                        {
                            Id = new Guid("13aeefcd-305e-46d6-a1b8-8afaf8e016b7"),
                            CurrentId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerDistanceInKilometers = 5.7000000000000002,
                            CustomerETA = new DateTime(2019, 11, 4, 16, 51, 2, 149, DateTimeKind.Local).AddTicks(3145),
                            CustomerId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerPhoneNumber = "0612345678",
                            DeliveredAt = new DateTime(2019, 11, 4, 16, 59, 2, 149, DateTimeKind.Local).AddTicks(3150),
                            DelivererId = new Guid("b97b134c-9f3d-4bef-9085-85b16b2f0cff"),
                            DueDate = new DateTime(2019, 11, 4, 18, 51, 2, 149, DateTimeKind.Local).AddTicks(3130),
                            PaymentMethod = 1,
                            Price = 14.26,
                            StartedAtId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            Status = 4,
                            Vehicle = 4,
                            WarehouseDistanceInKilometers = 13.6,
                            WarehouseETA = new DateTime(2019, 11, 4, 16, 21, 2, 149, DateTimeKind.Local).AddTicks(3136),
                            WarehouseId = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3"),
                            WarehousePickUpAt = new DateTime(2019, 11, 4, 16, 42, 2, 149, DateTimeKind.Local).AddTicks(3140)
                        },
                        new
                        {
                            Id = new Guid("8ea653a7-f384-406c-9e14-994e1bae27b4"),
                            CurrentId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerDistanceInKilometers = 5.7000000000000002,
                            CustomerETA = new DateTime(2019, 11, 4, 16, 51, 2, 149, DateTimeKind.Local).AddTicks(3399),
                            CustomerId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerPhoneNumber = "0612345678",
                            DeliveredAt = new DateTime(2019, 11, 4, 16, 59, 2, 149, DateTimeKind.Local).AddTicks(3404),
                            DelivererId = new Guid("03ab5306-01a8-400d-a43a-2edef178a187"),
                            DueDate = new DateTime(2019, 11, 4, 18, 51, 2, 149, DateTimeKind.Local).AddTicks(3382),
                            PaymentMethod = 1,
                            Price = 14.26,
                            StartedAtId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            Status = 4,
                            Vehicle = 4,
                            WarehouseDistanceInKilometers = 13.6,
                            WarehouseETA = new DateTime(2019, 11, 4, 16, 21, 2, 149, DateTimeKind.Local).AddTicks(3389),
                            WarehouseId = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3"),
                            WarehousePickUpAt = new DateTime(2019, 11, 4, 16, 42, 2, 149, DateTimeKind.Local).AddTicks(3393)
                        },
                        new
                        {
                            Id = new Guid("01b0fcd5-ecac-4158-972f-c13650563e7d"),
                            CurrentId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerDistanceInKilometers = 5.7000000000000002,
                            CustomerETA = new DateTime(2019, 11, 4, 16, 51, 2, 149, DateTimeKind.Local).AddTicks(3722),
                            CustomerId = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            CustomerPhoneNumber = "0612345678",
                            DeliveredAt = new DateTime(2019, 11, 4, 16, 59, 2, 149, DateTimeKind.Local).AddTicks(3727),
                            DelivererId = new Guid("1c8d26ac-0879-4bd4-aa45-ede7206c315d"),
                            DueDate = new DateTime(2019, 11, 4, 18, 51, 2, 149, DateTimeKind.Local).AddTicks(3702),
                            PaymentMethod = 1,
                            Price = 14.26,
                            StartedAtId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            Status = 4,
                            Vehicle = 4,
                            WarehouseDistanceInKilometers = 13.6,
                            WarehouseETA = new DateTime(2019, 11, 4, 16, 21, 2, 149, DateTimeKind.Local).AddTicks(3711),
                            WarehouseId = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3"),
                            WarehousePickUpAt = new DateTime(2019, 11, 4, 16, 42, 2, 149, DateTimeKind.Local).AddTicks(3717)
                        });
                });

            modelBuilder.Entity("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Category");

                    b.Property<Guid>("DelivererId");

                    b.Property<Guid>("DeliveryId");

                    b.Property<int>("Rating");

                    b.HasKey("Id");

                    b.HasIndex("DelivererId");

                    b.HasIndex("DeliveryId");

                    b.ToTable("Feedback");

                    b.HasData(
                        new
                        {
                            Id = new Guid("25c0ecf2-fc31-4576-a3b5-605a0cb5581b"),
                            Category = 0,
                            DelivererId = new Guid("1c8d26ac-0879-4bd4-aa45-ede7206c315d"),
                            DeliveryId = new Guid("01b0fcd5-ecac-4158-972f-c13650563e7d"),
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("65b6b5b4-6af2-45ee-bcd1-7473777b3eef"),
                            Category = 2,
                            DelivererId = new Guid("1c8d26ac-0879-4bd4-aa45-ede7206c315d"),
                            DeliveryId = new Guid("01b0fcd5-ecac-4158-972f-c13650563e7d"),
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("f44cf6b9-a710-4ac1-ac14-379f404a6dfc"),
                            Category = 1,
                            DelivererId = new Guid("1c8d26ac-0879-4bd4-aa45-ede7206c315d"),
                            DeliveryId = new Guid("01b0fcd5-ecac-4158-972f-c13650563e7d"),
                            Rating = 3
                        });
                });

            modelBuilder.Entity("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<Guid?>("DelivererId");

                    b.Property<bool>("IsWarehouse");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Place");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(6);

                    b.HasKey("Id");

                    b.HasIndex("DelivererId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            Address = "Lage Duin 38-14",
                            IsWarehouse = false,
                            Latitude = 52.322403999999999,
                            Longitude = 4.5969259999999998,
                            Place = "Bennebroek",
                            PostalCode = "2121CH"
                        },
                        new
                        {
                            Id = new Guid("f80cec78-70c7-43fa-be47-2f200e43eedf"),
                            Address = "Bijdorplaan 15",
                            IsWarehouse = false,
                            Latitude = 52.389454000000001,
                            Longitude = 4.6128770000000001,
                            Place = "Haarlem",
                            PostalCode = "2015CE"
                        },
                        new
                        {
                            Id = new Guid("bf78d3d2-cbc0-48a8-97f6-d0649e2408e3"),
                            Address = "Vlietweg 16",
                            IsWarehouse = true,
                            Latitude = 52.425825000000003,
                            Longitude = 4.6467109999999998,
                            Place = "Santpoort-Noord",
                            PostalCode = "2071KW"
                        });
                });

            modelBuilder.Entity("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("AcceptedAt");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("DelivererId");

                    b.Property<Guid>("DeliveryId");

                    b.Property<DateTime>("ExpiredAt");

                    b.Property<DateTime?>("RefusedAt");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("DelivererId");

                    b.HasIndex("DeliveryId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef93546b-9d74-4862-b746-7dfdd15ba844"),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 150, DateTimeKind.Local).AddTicks(4339),
                            DelivererId = new Guid("b97b134c-9f3d-4bef-9085-85b16b2f0cff"),
                            DeliveryId = new Guid("082f1eda-2985-4d2b-8add-80487f8edf66"),
                            ExpiredAt = new DateTime(2020, 11, 3, 16, 51, 2, 150, DateTimeKind.Local).AddTicks(4358),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("832b443c-909e-4b27-8059-2ec7894a9337"),
                            AcceptedAt = new DateTime(2019, 11, 4, 16, 59, 2, 151, DateTimeKind.Local).AddTicks(5106),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 151, DateTimeKind.Local).AddTicks(5089),
                            DelivererId = new Guid("77f3c372-e321-4263-ba7a-0f86ce51de56"),
                            DeliveryId = new Guid("3efb4583-bde7-4038-93ef-c7d30b845dd0"),
                            ExpiredAt = new DateTime(2019, 11, 4, 17, 1, 2, 151, DateTimeKind.Local).AddTicks(5114),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("0498ee91-92bc-408a-8a7a-18349769601a"),
                            AcceptedAt = new DateTime(2019, 11, 4, 16, 58, 2, 151, DateTimeKind.Local).AddTicks(5604),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 151, DateTimeKind.Local).AddTicks(5595),
                            DelivererId = new Guid("77f3c372-e321-4263-ba7a-0f86ce51de56"),
                            DeliveryId = new Guid("1e1909e9-de01-4221-bea1-80198de9254d"),
                            ExpiredAt = new DateTime(2019, 11, 4, 17, 1, 2, 151, DateTimeKind.Local).AddTicks(5611),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("8370e546-5bf9-4f95-9e8c-d50adc51e202"),
                            AcceptedAt = new DateTime(2019, 11, 4, 16, 59, 2, 151, DateTimeKind.Local).AddTicks(5728),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 151, DateTimeKind.Local).AddTicks(5720),
                            DelivererId = new Guid("fa8ec550-2863-4f01-82df-488d66004a60"),
                            DeliveryId = new Guid("7cb4d484-5fbc-4098-a4f5-bccfa1dd4a4a"),
                            ExpiredAt = new DateTime(2019, 11, 4, 17, 1, 2, 151, DateTimeKind.Local).AddTicks(5732),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("6dfa1e56-234d-4b4e-9ff6-b78447b6f27a"),
                            AcceptedAt = new DateTime(2019, 11, 4, 16, 58, 2, 151, DateTimeKind.Local).AddTicks(5928),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 151, DateTimeKind.Local).AddTicks(5922),
                            DelivererId = new Guid("fa8ec550-2863-4f01-82df-488d66004a60"),
                            DeliveryId = new Guid("061d5bc1-62f3-4372-b354-77a4b8be26c0"),
                            ExpiredAt = new DateTime(2019, 11, 4, 17, 1, 2, 151, DateTimeKind.Local).AddTicks(5932),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("feabedb2-b543-48a9-9bc3-c8fc13111308"),
                            AcceptedAt = new DateTime(2019, 11, 4, 16, 52, 2, 151, DateTimeKind.Local).AddTicks(6027),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 151, DateTimeKind.Local).AddTicks(6022),
                            DelivererId = new Guid("c26682bd-d8bf-4698-a00e-02d059a2498d"),
                            DeliveryId = new Guid("819363c4-434f-4934-bc2b-1d7de4ddef7a"),
                            ExpiredAt = new DateTime(2019, 11, 4, 17, 1, 2, 151, DateTimeKind.Local).AddTicks(6031),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("f31dfe65-9b15-4ac1-9c9c-57cdc01f8d88"),
                            AcceptedAt = new DateTime(2019, 11, 4, 16, 53, 2, 151, DateTimeKind.Local).AddTicks(6117),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 151, DateTimeKind.Local).AddTicks(6112),
                            DelivererId = new Guid("c26682bd-d8bf-4698-a00e-02d059a2498d"),
                            DeliveryId = new Guid("0415d421-3359-4117-a697-092186ae2569"),
                            ExpiredAt = new DateTime(2019, 11, 4, 17, 1, 2, 151, DateTimeKind.Local).AddTicks(6121),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("53580fad-c009-4c5f-928c-5d9808691616"),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 151, DateTimeKind.Local).AddTicks(6209),
                            DelivererId = new Guid("c26682bd-d8bf-4698-a00e-02d059a2498d"),
                            DeliveryId = new Guid("8cd77e0d-784b-4440-80e9-cd889395a420"),
                            ExpiredAt = new DateTime(2019, 11, 4, 17, 1, 2, 151, DateTimeKind.Local).AddTicks(6222),
                            RefusedAt = new DateTime(2019, 11, 4, 16, 52, 2, 151, DateTimeKind.Local).AddTicks(6216),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("4d71bdb6-f607-41be-b3a4-59139b8a9a5c"),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 151, DateTimeKind.Local).AddTicks(6532),
                            DelivererId = new Guid("c26682bd-d8bf-4698-a00e-02d059a2498d"),
                            DeliveryId = new Guid("8800377f-f8c9-4db8-8fed-60b4fa2b4bb6"),
                            ExpiredAt = new DateTime(2019, 11, 4, 17, 1, 2, 151, DateTimeKind.Local).AddTicks(6542),
                            RefusedAt = new DateTime(2019, 11, 4, 16, 53, 2, 151, DateTimeKind.Local).AddTicks(6538),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("6377aa78-8601-4000-af20-d91ce8d34638"),
                            AcceptedAt = new DateTime(2019, 11, 4, 16, 53, 2, 151, DateTimeKind.Local).AddTicks(6641),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 151, DateTimeKind.Local).AddTicks(6634),
                            DelivererId = new Guid("546210b1-6ec8-4d64-b058-b3fa7e0740aa"),
                            DeliveryId = new Guid("8800377f-f8c9-4db8-8fed-60b4fa2b4bb6"),
                            ExpiredAt = new DateTime(2019, 11, 4, 17, 1, 2, 151, DateTimeKind.Local).AddTicks(6646),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("ef398353-f31d-4503-9042-0f6429a0e6f1"),
                            AcceptedAt = new DateTime(2019, 11, 4, 16, 53, 2, 151, DateTimeKind.Local).AddTicks(6745),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 151, DateTimeKind.Local).AddTicks(6739),
                            DelivererId = new Guid("546210b1-6ec8-4d64-b058-b3fa7e0740aa"),
                            DeliveryId = new Guid("c4f626f8-e626-45b9-8548-b1d922a49e0d"),
                            ExpiredAt = new DateTime(2019, 11, 4, 17, 1, 2, 151, DateTimeKind.Local).AddTicks(6751),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c89945f3-dfcd-491c-bee4-c752279e61a7"),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 151, DateTimeKind.Local).AddTicks(6832),
                            DelivererId = new Guid("546210b1-6ec8-4d64-b058-b3fa7e0740aa"),
                            DeliveryId = new Guid("4aea94b7-a21f-472f-be50-154fead4ac8c"),
                            ExpiredAt = new DateTime(2019, 11, 4, 17, 1, 2, 151, DateTimeKind.Local).AddTicks(6843),
                            RefusedAt = new DateTime(2019, 11, 4, 16, 54, 2, 151, DateTimeKind.Local).AddTicks(6838),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("2fc78d41-a4ee-42c4-be96-e222aca5db1c"),
                            AcceptedAt = new DateTime(2019, 11, 4, 16, 59, 2, 151, DateTimeKind.Local).AddTicks(6935),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 151, DateTimeKind.Local).AddTicks(6928),
                            DelivererId = new Guid("5fc08418-6e23-4de8-88b0-1c513ddaf40d"),
                            DeliveryId = new Guid("c4f626f8-e626-45b9-8548-b1d922a49e0d"),
                            ExpiredAt = new DateTime(2019, 11, 4, 17, 1, 2, 151, DateTimeKind.Local).AddTicks(6940),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("f7bdd7eb-0c33-4f13-8a2a-9667e4c49152"),
                            AcceptedAt = new DateTime(2019, 11, 4, 16, 59, 2, 151, DateTimeKind.Local).AddTicks(7087),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 151, DateTimeKind.Local).AddTicks(7080),
                            DelivererId = new Guid("5fc08418-6e23-4de8-88b0-1c513ddaf40d"),
                            DeliveryId = new Guid("4aea94b7-a21f-472f-be50-154fead4ac8c"),
                            ExpiredAt = new DateTime(2019, 11, 4, 17, 1, 2, 151, DateTimeKind.Local).AddTicks(7092),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("f5b62a35-fa21-4660-bf57-e30df51a2ff2"),
                            AcceptedAt = new DateTime(2019, 11, 4, 17, 0, 2, 151, DateTimeKind.Local).AddTicks(7198),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 151, DateTimeKind.Local).AddTicks(7192),
                            DelivererId = new Guid("f2f458f3-819e-46b3-be44-554f6a2fad93"),
                            DeliveryId = new Guid("3558b0eb-af94-4e37-b94a-8d82500cca37"),
                            ExpiredAt = new DateTime(2019, 11, 4, 17, 1, 2, 151, DateTimeKind.Local).AddTicks(7203),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("60ecff74-32ca-4d29-b5c4-a03b0148825c"),
                            AcceptedAt = new DateTime(2019, 11, 4, 17, 0, 2, 151, DateTimeKind.Local).AddTicks(7302),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 151, DateTimeKind.Local).AddTicks(7295),
                            DelivererId = new Guid("f2f458f3-819e-46b3-be44-554f6a2fad93"),
                            DeliveryId = new Guid("54b90b3c-f3e9-47cc-a507-7e0a8fea7fb0"),
                            ExpiredAt = new DateTime(2019, 11, 4, 17, 1, 2, 151, DateTimeKind.Local).AddTicks(7309),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("6f13c993-b14b-4ef0-9515-98aa1830435c"),
                            AcceptedAt = new DateTime(2019, 11, 4, 17, 0, 2, 151, DateTimeKind.Local).AddTicks(7400),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 151, DateTimeKind.Local).AddTicks(7393),
                            DelivererId = new Guid("a6578db0-5e35-4a6b-967b-2d546e16b6f7"),
                            DeliveryId = new Guid("7d5dd904-43ab-4ee4-9b72-78ec0caf629b"),
                            ExpiredAt = new DateTime(2019, 11, 4, 17, 1, 2, 151, DateTimeKind.Local).AddTicks(7403),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("118ce4db-2629-4417-ab31-b8b355f24fdd"),
                            AcceptedAt = new DateTime(2019, 11, 4, 17, 0, 2, 151, DateTimeKind.Local).AddTicks(7478),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 151, DateTimeKind.Local).AddTicks(7472),
                            DelivererId = new Guid("1c8d26ac-0879-4bd4-aa45-ede7206c315d"),
                            DeliveryId = new Guid("01b0fcd5-ecac-4158-972f-c13650563e7d"),
                            ExpiredAt = new DateTime(2019, 11, 4, 17, 1, 2, 151, DateTimeKind.Local).AddTicks(7484),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("b84e4c03-339b-4ce2-81a6-e9176ecbad92"),
                            AcceptedAt = new DateTime(2019, 11, 4, 17, 0, 2, 151, DateTimeKind.Local).AddTicks(7577),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 151, DateTimeKind.Local).AddTicks(7571),
                            DelivererId = new Guid("03ab5306-01a8-400d-a43a-2edef178a187"),
                            DeliveryId = new Guid("8ea653a7-f384-406c-9e14-994e1bae27b4"),
                            ExpiredAt = new DateTime(2019, 11, 4, 17, 1, 2, 151, DateTimeKind.Local).AddTicks(7583),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("be512cf1-8c41-467d-b34f-e02088eb9f4d"),
                            AcceptedAt = new DateTime(2019, 11, 4, 17, 0, 2, 151, DateTimeKind.Local).AddTicks(7676),
                            CreatedAt = new DateTime(2019, 11, 4, 16, 51, 2, 151, DateTimeKind.Local).AddTicks(7665),
                            DelivererId = new Guid("1566979b-9fa6-4a51-8e67-08509ce79106"),
                            DeliveryId = new Guid("9c90af37-6ead-4b3c-ba11-d1c2e8634bba"),
                            ExpiredAt = new DateTime(2019, 11, 4, 17, 1, 2, 151, DateTimeKind.Local).AddTicks(7681),
                            Status = 1
                        });
                });

            modelBuilder.Entity("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("EmailAddress")
                        .IsRequired();

                    b.Property<string>("Hash")
                        .IsRequired();

                    b.Property<string>("Token");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasFilter("[Token] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Deliverer", b =>
                {
                    b.HasBaseType("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.User");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<double>("Fare");

                    b.Property<Guid>("HomeId");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("Range");

                    b.Property<int>("Vehicle");

                    b.HasIndex("HomeId");

                    b.HasDiscriminator().HasValue("Deliverer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1c8d26ac-0879-4bd4-aa45-ede7206c315d"),
                            EmailAddress = "test1@test.test",
                            Hash = "bc547750b92797f955b36112cc9bdd5cddf7d0862151d03a167ada8995aa24a9ad24610b36a68bc02da24141ee51670aea13ed6469099a4453f335cb239db5da",
                            DateOfBirth = new DateTime(1997, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 5.4100000000000001,
                            HomeId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            PhoneNumber = "0612345678",
                            Range = 5,
                            Vehicle = 4
                        },
                        new
                        {
                            Id = new Guid("a6578db0-5e35-4a6b-967b-2d546e16b6f7"),
                            EmailAddress = "test2@test.test",
                            Hash = "bc547750b92797f955b36112cc9bdd5cddf7d0862151d03a167ada8995aa24a9ad24610b36a68bc02da24141ee51670aea13ed6469099a4453f335cb239db5da",
                            DateOfBirth = new DateTime(1997, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 5.4100000000000001,
                            HomeId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            PhoneNumber = "0612345678",
                            Range = 40,
                            Vehicle = 4
                        },
                        new
                        {
                            Id = new Guid("03ab5306-01a8-400d-a43a-2edef178a187"),
                            EmailAddress = "test3@test.test",
                            Hash = "bc547750b92797f955b36112cc9bdd5cddf7d0862151d03a167ada8995aa24a9ad24610b36a68bc02da24141ee51670aea13ed6469099a4453f335cb239db5da",
                            DateOfBirth = new DateTime(1997, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 5.4100000000000001,
                            HomeId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            PhoneNumber = "0612345678",
                            Range = 40,
                            Vehicle = 4
                        },
                        new
                        {
                            Id = new Guid("4a18c314-3c45-4eea-b893-680eb09c1abe"),
                            EmailAddress = "test4@test.test",
                            Hash = "bc547750b92797f955b36112cc9bdd5cddf7d0862151d03a167ada8995aa24a9ad24610b36a68bc02da24141ee51670aea13ed6469099a4453f335cb239db5da",
                            DateOfBirth = new DateTime(1997, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 5.4100000000000001,
                            HomeId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            PhoneNumber = "0612345678",
                            Range = 40,
                            Vehicle = 4
                        },
                        new
                        {
                            Id = new Guid("b97b134c-9f3d-4bef-9085-85b16b2f0cff"),
                            EmailAddress = "test5@test.test",
                            Hash = "bc547750b92797f955b36112cc9bdd5cddf7d0862151d03a167ada8995aa24a9ad24610b36a68bc02da24141ee51670aea13ed6469099a4453f335cb239db5da",
                            DateOfBirth = new DateTime(1997, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 5.4100000000000001,
                            HomeId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            PhoneNumber = "0612345678",
                            Range = 40,
                            Vehicle = 4
                        },
                        new
                        {
                            Id = new Guid("1566979b-9fa6-4a51-8e67-08509ce79106"),
                            EmailAddress = "test6@test.test",
                            Hash = "bc547750b92797f955b36112cc9bdd5cddf7d0862151d03a167ada8995aa24a9ad24610b36a68bc02da24141ee51670aea13ed6469099a4453f335cb239db5da",
                            DateOfBirth = new DateTime(1997, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 5.4100000000000001,
                            HomeId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            PhoneNumber = "0612345678",
                            Range = 40,
                            Vehicle = 2
                        },
                        new
                        {
                            Id = new Guid("77f3c372-e321-4263-ba7a-0f86ce51de56"),
                            EmailAddress = "test7@test.test",
                            Hash = "bc547750b92797f955b36112cc9bdd5cddf7d0862151d03a167ada8995aa24a9ad24610b36a68bc02da24141ee51670aea13ed6469099a4453f335cb239db5da",
                            DateOfBirth = new DateTime(1997, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 5.4100000000000001,
                            HomeId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            PhoneNumber = "0612345678",
                            Range = 40,
                            Vehicle = 4
                        },
                        new
                        {
                            Id = new Guid("fa8ec550-2863-4f01-82df-488d66004a60"),
                            EmailAddress = "test8@test.test",
                            Hash = "bc547750b92797f955b36112cc9bdd5cddf7d0862151d03a167ada8995aa24a9ad24610b36a68bc02da24141ee51670aea13ed6469099a4453f335cb239db5da",
                            DateOfBirth = new DateTime(1997, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 5.4100000000000001,
                            HomeId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            PhoneNumber = "0612345678",
                            Range = 40,
                            Vehicle = 4
                        },
                        new
                        {
                            Id = new Guid("c26682bd-d8bf-4698-a00e-02d059a2498d"),
                            EmailAddress = "test9@test.test",
                            Hash = "bc547750b92797f955b36112cc9bdd5cddf7d0862151d03a167ada8995aa24a9ad24610b36a68bc02da24141ee51670aea13ed6469099a4453f335cb239db5da",
                            DateOfBirth = new DateTime(1997, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 5.4100000000000001,
                            HomeId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            PhoneNumber = "0612345678",
                            Range = 40,
                            Vehicle = 4
                        },
                        new
                        {
                            Id = new Guid("546210b1-6ec8-4d64-b058-b3fa7e0740aa"),
                            EmailAddress = "test10@test.test",
                            Hash = "bc547750b92797f955b36112cc9bdd5cddf7d0862151d03a167ada8995aa24a9ad24610b36a68bc02da24141ee51670aea13ed6469099a4453f335cb239db5da",
                            DateOfBirth = new DateTime(1997, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 5.4100000000000001,
                            HomeId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            PhoneNumber = "0612345678",
                            Range = 40,
                            Vehicle = 4
                        },
                        new
                        {
                            Id = new Guid("5fc08418-6e23-4de8-88b0-1c513ddaf40d"),
                            EmailAddress = "test11@test.test",
                            Hash = "bc547750b92797f955b36112cc9bdd5cddf7d0862151d03a167ada8995aa24a9ad24610b36a68bc02da24141ee51670aea13ed6469099a4453f335cb239db5da",
                            DateOfBirth = new DateTime(1997, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 5.4100000000000001,
                            HomeId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            PhoneNumber = "0612345678",
                            Range = 40,
                            Vehicle = 4
                        },
                        new
                        {
                            Id = new Guid("f2f458f3-819e-46b3-be44-554f6a2fad93"),
                            EmailAddress = "test12@test.test",
                            Hash = "bc547750b92797f955b36112cc9bdd5cddf7d0862151d03a167ada8995aa24a9ad24610b36a68bc02da24141ee51670aea13ed6469099a4453f335cb239db5da",
                            DateOfBirth = new DateTime(1997, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 5.4100000000000001,
                            HomeId = new Guid("d163b296-fc5c-4f1a-b56b-9fae13640a37"),
                            PhoneNumber = "0612345678",
                            Range = 40,
                            Vehicle = 4
                        });
                });

            modelBuilder.Entity("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Availability", b =>
                {
                    b.HasOne("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Deliverer", "Deliverer")
                        .WithMany("Availabilities")
                        .HasForeignKey("DelivererId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Delivery", b =>
                {
                    b.HasOne("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Location", "Current")
                        .WithMany()
                        .HasForeignKey("CurrentId");

                    b.HasOne("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Location", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Deliverer", "Deliverer")
                        .WithMany("Deliveries")
                        .HasForeignKey("DelivererId");

                    b.HasOne("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Location", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Feedback", b =>
                {
                    b.HasOne("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Deliverer", "Deliverer")
                        .WithMany("Feedback")
                        .HasForeignKey("DelivererId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Delivery", "Delivery")
                        .WithMany("Feedback")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Location", b =>
                {
                    b.HasOne("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Deliverer")
                        .WithMany("Warehouses")
                        .HasForeignKey("DelivererId");
                });

            modelBuilder.Entity("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Notification", b =>
                {
                    b.HasOne("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Deliverer", "Deliverer")
                        .WithMany("Notifications")
                        .HasForeignKey("DelivererId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Delivery", "Delivery")
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Deliverer", b =>
                {
                    b.HasOne("BezorgDirect.BezorgersApplicatie.BusinessLogic.Models.Location", "Home")
                        .WithMany()
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
